### PR TITLE
Foreign Key Constraint Support

### PR DESCRIPTION
**Pull request by chrisjpalmer**
This pull request enables foreign key constraint support for the tengo library. It includes support for cross schema constraints and correctly handles constraints with the RESTRICT mode.

### CODE REVIEW

**Comment by chrisjpalmer** [comment]
Remembered to put it into the foreign keys branch!

**Comment by chrisjpalmer** [comment]
Hi Evan. I have completed the tests for constraints and also made an amendment to the the Constraint struct. It contained `ColumnName string` and I changed this to be `Column *Column` so it is more consistent with the rest of the application. I have performed some testing on a bunch of databases which I administer and it seems to be working very well. Obviously you would want to perform your own testing to verify that everything works.

Looking forward to hearing from you.

Chris

**Comment by evanelias** [comment]
Awesome, this is great, thanks again Chris! I'll review and test this
weekend.

**Comment by evanelias** [comment]
Functionality looks perfect! Thanks for adding the unit tests too, this is excellent.

I'm going to go ahead and merge this into the `foreign_keys` branch, and then add some quick style changes on top in a separate commit. It also looks like some recent README changes were inadvertently reverted here; I'll fix those too. (I think what happened is I updated the README here in f7108f254, but I didn't update the vendored version in [skeema/skeema](http://github.com/skeema/skeema) since it was only a documentation change.)

There are a few other things I want to look into on my end before merging `foreign_keys` into `master`, and then updating the vendored version in [skeema/skeema](http://github.com/skeema/skeema). It's just the items I mentioned under "Future considerations on my end" in my comment on skeema/skeema#8. Might take a couple more weeks on that, apologies in advance if so -- I'm in the process of switching to a new computer at home and still have a lot of development-related things to set up :)

**Pull request merged**
